#define DEBUG 1

// I2CCom
#define I2C_INPUT_BUFFER_MAX_LENGTH 128
#define I2C_BUFFER_SIZE 32
#define PACKET_END_IDENTIFIER '!'

// CLOCK
#define TIME_SET "10"
#define TIME_SET_REQUEST "11"
#define TIME_IS_SET_REQUEST "12"

// SENSOR
#define SENSOR_INTERVAL_SET "20"
#define SENSOR_TEMPERATURE_REQUEST "21"
#define SENSOR_HUMIDITY_REQUEST "22"
#define SENSOR_INTERVAL_REQUEST "23"
#define SENSOR_CO2_REQUEST "24"
#define SENSOR_INTERVAL_DEFAULT_SECONDS 90

// ALARM
#define ALARM_TIME_SET "31"
#define ALARM_STATUS_SET "32"
#define ALARM_TIME_INTERVAL_SET "33"
#define ALARM_TIME_REQUEST "34"
#define ALARM_STATUS_REQUEST "35"
#define ALARM_TIME_INTERVAL_REQUEST "36"
#define ALARM_TIME_INTERVAL_DEFAULT_SECONDS 10

// LED
#define LED_COLOR_SET "40"
#define LED_COLOR_REQUEST "41"
#define LED_COLOR_DEFAULT_R 123
#define LED_COLOR_DEFAULT_G 123
#define LED_COLOR_DEFAULT_B 123

// PINS
#define R_LED_PIN 11
#define G_LED_PIN 10
#define B_LED_PIN 9
#define MQ135_PIN A0
#define DHT11_PIN 2

// IDENTIFIERS
#define HOURS 0
#define MINUTES 1
#define SECONDS 2
#define COLOR_R 0
#define COLOR_G 1
#define COLOR_B 2
